//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:34:25 AM CEST 
//
package mil.army.usareur.g3.mcsd.CotBindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="notify" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wilcoby" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="authority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="streamto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "any"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "notify", required = true)
    protected String notify;
    @XmlAttribute(name = "wilcoby")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar wilcoby;
    @XmlAttribute(name = "priority")
    protected String priority;
    @XmlAttribute(name = "version")
    protected double version;
    @XmlAttribute(name = "to")
    protected String to;
    @XmlAttribute(name = "authority")
    protected String authority;
    @XmlAttribute(name = "streamto")
    protected String streamto;

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null     {@link Element }
     * {@link Object }
     *
     *
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the notify property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNotify() {
        return notify;
    }

    /**
     * Sets the value of the notify property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNotify(String value) {
        this.notify = value;
    }

    /**
     * Gets the value of the wilcoby property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getWilcoby() {
        return wilcoby;
    }

    /**
     * Sets the value of the wilcoby property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setWilcoby(XMLGregorianCalendar value) {
        this.wilcoby = value;
    }

    /**
     * Gets the value of the priority property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setVersion(double value) {
        this.version = value;
    }

    /**
     * Gets the value of the to property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the authority property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuthority(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the streamto property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStreamto() {
        return streamto;
    }

    /**
     * Sets the value of the streamto property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setStreamto(String value) {
        this.streamto = value;
    }

}
