//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:34:26 AM CEST 
//
package mil.army.usareur.g3.mcsd.CotBindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="azimuth">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxExclusive value="360"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="elevation">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="-90"/>
 *             &lt;maxInclusive value="90"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="roll">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minExclusive value="-180"/>
 *             &lt;maxInclusive value="180"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fov">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxExclusive value="360"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vfov">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxExclusive value="360"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="north">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxExclusive value="360"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="range">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "any"
})
@XmlRootElement(name = "sensor")
public class Sensor {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "azimuth")
    protected double azimuth;
    @XmlAttribute(name = "elevation")
    protected double elevation;
    @XmlAttribute(name = "roll")
    protected double roll;
    @XmlAttribute(name = "fov")
    protected double fov;
    @XmlAttribute(name = "vfov")
    protected double vfov;
    @XmlAttribute(name = "north")
    protected double north;
    @XmlAttribute(name = "version")
    protected double version;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "model")
    protected String model;
    @XmlAttribute(name = "range")
    protected double range;

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null     {@link Object }
     * {@link Element }
     *
     *
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the azimuth property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getAzimuth() {
        return azimuth;
    }

    /**
     * Sets the value of the azimuth property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setAzimuth(double value) {
        this.azimuth = value;
    }

    /**
     * Gets the value of the elevation property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setElevation(double value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the roll property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getRoll() {
        return roll;
    }

    /**
     * Sets the value of the roll property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setRoll(double value) {
        this.roll = value;
    }

    /**
     * Gets the value of the fov property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getFov() {
        return fov;
    }

    /**
     * Sets the value of the fov property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setFov(double value) {
        this.fov = value;
    }

    /**
     * Gets the value of the vfov property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getVfov() {
        return vfov;
    }

    /**
     * Sets the value of the vfov property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setVfov(double value) {
        this.vfov = value;
    }

    /**
     * Gets the value of the north property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getNorth() {
        return north;
    }

    /**
     * Sets the value of the north property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setNorth(double value) {
        this.north = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setVersion(double value) {
        this.version = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the range property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setRange(double value) {
        this.range = value;
    }

}
