//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:34:27 AM CEST 
//
package mil.army.usareur.g3.mcsd.CotBindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ellipse" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="major" use="required" type="{}nonNegativeDecimal" />
 *                 &lt;attribute name="minor" use="required" type="{}nonNegativeDecimal" />
 *                 &lt;attribute name="angle" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="extrude" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="polyline" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vertex" maxOccurs="unbounded" minOccurs="2">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="lat" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 &lt;minInclusive value="-90"/>
 *                                 &lt;maxInclusive value="90"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="lon" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 &lt;minInclusive value="-180"/>
 *                                 &lt;maxInclusive value="180"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="hae" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="closed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dxf" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ellipse",
    "polyline",
    "dxf"
})
@XmlRootElement(name = "shape")
public class Shape {

    protected Shape.Ellipse ellipse;
    protected Shape.Polyline polyline;
    protected Shape.Dxf dxf;
    @XmlAttribute(name = "version")
    protected double version;

    /**
     * Gets the value of the ellipse property.
     *
     * @return possible object is {@link Shape.Ellipse }
     *
     */
    public Shape.Ellipse getEllipse() {
        return ellipse;
    }

    /**
     * Sets the value of the ellipse property.
     *
     * @param value allowed object is {@link Shape.Ellipse }
     *
     */
    public void setEllipse(Shape.Ellipse value) {
        this.ellipse = value;
    }

    /**
     * Gets the value of the polyline property.
     *
     * @return possible object is {@link Shape.Polyline }
     *
     */
    public Shape.Polyline getPolyline() {
        return polyline;
    }

    /**
     * Sets the value of the polyline property.
     *
     * @param value allowed object is {@link Shape.Polyline }
     *
     */
    public void setPolyline(Shape.Polyline value) {
        this.polyline = value;
    }

    /**
     * Gets the value of the dxf property.
     *
     * @return possible object is {@link Shape.Dxf }
     *
     */
    public Shape.Dxf getDxf() {
        return dxf;
    }

    /**
     * Sets the value of the dxf property.
     *
     * @param value allowed object is {@link Shape.Dxf }
     *
     */
    public void setDxf(Shape.Dxf value) {
        this.dxf = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setVersion(double value) {
        this.version = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Dxf {

        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "level")
        protected int level;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list          {@link Element }
         * {@link Object }
         *
         *
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the level property.
         *
         * @return possible object is {@link int }
         *
         */
        public int getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         *
         * @param value allowed object is {@link int }
         *
         */
        public void setLevel(int value) {
            this.level = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="major" use="required" type="{}nonNegativeDecimal" />
     *       &lt;attribute name="minor" use="required" type="{}nonNegativeDecimal" />
     *       &lt;attribute name="angle" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="extrude" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Ellipse {

        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "major", required = true)
        protected double major;
        @XmlAttribute(name = "minor", required = true)
        protected double minor;
        @XmlAttribute(name = "angle", required = true)
        protected double angle;
        @XmlAttribute(name = "level")
        protected int level;
        @XmlAttribute(name = "extrude")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected int extrude;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list          {@link Element }
         * {@link Object }
         *
         *
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the major property.
         *
         * @return possible object is {@link double }
         *
         */
        public double getMajor() {
            return major;
        }

        /**
         * Sets the value of the major property.
         *
         * @param value allowed object is {@link double }
         *
         */
        public void setMajor(double value) {
            this.major = value;
        }

        /**
         * Gets the value of the minor property.
         *
         * @return possible object is {@link double }
         *
         */
        public double getMinor() {
            return minor;
        }

        /**
         * Sets the value of the minor property.
         *
         * @param value allowed object is {@link double }
         *
         */
        public void setMinor(double value) {
            this.minor = value;
        }

        /**
         * Gets the value of the angle property.
         *
         * @return possible object is {@link double }
         *
         */
        public double getAngle() {
            return angle;
        }

        /**
         * Sets the value of the angle property.
         *
         * @param value allowed object is {@link double }
         *
         */
        public void setAngle(double value) {
            this.angle = value;
        }

        /**
         * Gets the value of the level property.
         *
         * @return possible object is {@link int }
         *
         */
        public int getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         *
         * @param value allowed object is {@link int }
         *
         */
        public void setLevel(int value) {
            this.level = value;
        }

        /**
         * Gets the value of the extrude property.
         *
         * @return possible object is {@link int }
         *
         */
        public int getExtrude() {
            return extrude;
        }

        /**
         * Sets the value of the extrude property.
         *
         * @param value allowed object is {@link int }
         *
         */
        public void setExtrude(int value) {
            this.extrude = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vertex" maxOccurs="unbounded" minOccurs="2">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="lat" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       &lt;minInclusive value="-90"/>
     *                       &lt;maxInclusive value="90"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="lon" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       &lt;minInclusive value="-180"/>
     *                       &lt;maxInclusive value="180"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="hae" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="closed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertex"
    })
    public static class Polyline {

        @XmlElement(required = true)
        protected List<Shape.Polyline.Vertex> vertex;
        @XmlAttribute(name = "level")
        protected int level;
        @XmlAttribute(name = "closed")
        protected Boolean closed;

        /**
         * Gets the value of the vertex property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the vertex property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVertex().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Shape.Polyline.Vertex }
         *
         *
         */
        public List<Shape.Polyline.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<Shape.Polyline.Vertex>();
            }
            return this.vertex;
        }

        /**
         * Gets the value of the level property.
         *
         * @return possible object is {@link int }
         *
         */
        public int getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         *
         * @param value allowed object is {@link int }
         *
         */
        public void setLevel(int value) {
            this.level = value;
        }

        /**
         * Gets the value of the closed property.
         *
         * @return possible object is {@link Boolean }
         *
         */
        public boolean isClosed() {
            if (closed == null) {
                return true;
            } else {
                return closed;
            }
        }

        /**
         * Sets the value of the closed property.
         *
         * @param value allowed object is {@link Boolean }
         *
         */
        public void setClosed(Boolean value) {
            this.closed = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="lat" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             &lt;minInclusive value="-90"/>
         *             &lt;maxInclusive value="90"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="lon" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             &lt;minInclusive value="-180"/>
         *             &lt;maxInclusive value="180"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="hae" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Vertex {

            @XmlAttribute(name = "lat", required = true)
            protected double lat;
            @XmlAttribute(name = "lon", required = true)
            protected double lon;
            @XmlAttribute(name = "hae")
            protected double hae;

            /**
             * Gets the value of the lat property.
             *
             * @return possible object is {@link double }
             *
             */
            public double getLat() {
                return lat;
            }

            /**
             * Sets the value of the lat property.
             *
             * @param value allowed object is {@link double }
             *
             */
            public void setLat(double value) {
                this.lat = value;
            }

            /**
             * Gets the value of the lon property.
             *
             * @return possible object is {@link double }
             *
             */
            public double getLon() {
                return lon;
            }

            /**
             * Sets the value of the lon property.
             *
             * @param value allowed object is {@link double }
             *
             */
            public void setLon(double value) {
                this.lon = value;
            }

            /**
             * Gets the value of the hae property.
             *
             * @return possible object is {@link double }
             *
             */
            public double getHae() {
                return hae;
            }

            /**
             * Sets the value of the hae property.
             *
             * @param value allowed object is {@link double }
             *
             */
            public void setHae(double value) {
                this.hae = value;
            }

        }

    }

}
