//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.24 at 11:34:28 AM CEST 
//
package mil.army.usareur.g3.mcsd.CotBindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="course" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxExclusive value="360"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="speed" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="slope">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="-90.0"/>
 *             &lt;maxInclusive value="90.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="eCourse" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="eSpeed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="eSlope" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "any"
})
@XmlRootElement(name = "track")
public class Track {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "course", required = true)
    protected double course;
    @XmlAttribute(name = "speed", required = true)
    protected double speed;
    @XmlAttribute(name = "slope")
    protected double slope;
    @XmlAttribute(name = "eCourse")
    protected double eCourse;
    @XmlAttribute(name = "eSpeed")
    protected double eSpeed;
    @XmlAttribute(name = "eSlope")
    protected double eSlope;
    @XmlAttribute(name = "version")
    protected double version;

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list      {@link Object }
     * {@link Element }
     *
     *
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the course property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getCourse() {
        return course;
    }

    /**
     * Sets the value of the course property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setCourse(double value) {
        this.course = value;
    }

    /**
     * Gets the value of the speed property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setSpeed(double value) {
        this.speed = value;
    }

    /**
     * Gets the value of the slope property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getSlope() {
        return slope;
    }

    /**
     * Sets the value of the slope property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setSlope(double value) {
        this.slope = value;
    }

    /**
     * Gets the value of the eCourse property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getECourse() {
        return eCourse;
    }

    /**
     * Sets the value of the eCourse property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setECourse(double value) {
        this.eCourse = value;
    }

    /**
     * Gets the value of the eSpeed property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getESpeed() {
        return eSpeed;
    }

    /**
     * Sets the value of the eSpeed property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setESpeed(double value) {
        this.eSpeed = value;
    }

    /**
     * Gets the value of the eSlope property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getESlope() {
        return eSlope;
    }

    /**
     * Sets the value of the eSlope property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setESlope(double value) {
        this.eSlope = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link double }
     *
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link double }
     *
     */
    public void setVersion(double value) {
        this.version = value;
    }

}
